### ISSUE TITLE
Graphical glitches with multimonitor setups on Wayland

### ISSUE THREAD

**Issue by SqrHornet** [a-parhom/LightlyShaders#28] opened 2022-02-09 22:15 UTC
Chromium browser
![image](https://user-images.githubusercontent.com/84623999/153299166-802c44a8-4173-4ec6-ae1a-fbe04e97a017.png)

Brave browser
![image](https://user-images.githubusercontent.com/84623999/153299200-3a4c89e6-8d5c-4108-9f6c-e8e216d68953.png)

**Comment by a-parhom** [comment] 2022-02-10 17:13
The cause of it can be the gtk theme that's being used. Try changing the theme to Breeze and let me know if the issue persists.

**Comment by SqrHornet** [comment] 2022-02-11 08:21
I checked with chromium builtin theme and breeze GTK and issue persists. Maybe it's somehow related to HiDPI display I'm using. I'll try to check it on other pc when I'll have some free time.

**Comment by a-parhom** [comment] 2022-02-21 12:01
I couldn't reproduce this with Chromium, Brave and Google Chrome on X11 in a VM on a Mac with 200% scaling.

**Comment by Sojiro84** [comment] 2022-05-14 09:26
I have the black corner bug as well. I see it on all apps, Firefox/Chromium/Kate/Konsole etc. Below a example of Kate.

![image](https://user-images.githubusercontent.com/13678578/168419806-405514af-9008-46c6-a3b0-79746b969a3a.png)

Any idea how to fix this? I tried using the default Breeze theme and turning off contrast/blur but no luck.

**Comment by a-parhom** [comment] 2022-05-14 09:51
Tell me, please, your Plasma version, which hardware do you use and is this on X11 or Wayland?

**Comment by a-parhom** [comment] 2022-05-14 09:53
If this is only on Wayland, please, tell me if use any scaling?

**Comment by a-parhom** [comment] 2022-05-14 11:33
Also, make sure that you are using the latest code, because Wayland scaling has been improved in recent commits.

**Comment by Sojiro84** [comment] 2022-05-14 12:47
I downloaded and installed it today. Got the latest master. By default I run Wayland and there the issue is visible. Currently I switched to X11 and there the problem isn't visible. I am not using any scaling. All monitors at 100%.

I am running Arch on a AMD CPU and GPU using MESA.

![image](https://user-images.githubusercontent.com/13678578/168426339-fbf7396c-e730-4b06-9ad2-4ed474019454.png)

**Comment by a-parhom** [comment] 2022-05-14 23:50
Just tested this in VirtualBox on Manjaro with Wayland and Plasma 5.24.5 and could not reproduce it (see screenshot). Maybe there is something connected with your GPU. Unfortunately, I'm not able to test it on an AMD GPU now.
![VirtualBox_Manjaro_15_05_2022_02_46_36](https://user-images.githubusercontent.com/13824167/168451614-21bda88f-2f60-43e1-a9dc-1b1641e51f52.png)

**Comment by Sojiro84** [comment] 2022-05-17 06:44
Thanks for testing. I am just as confused as you. So strange.

Well, I guess I shall wait for Plasma 5.25 and I am assuming you need to update your shader as well to make it compatible, and then see if it works perfectly seeing as 5.25 has the korner bug fixed!

**Comment by fafafwawe** [comment] 2022-05-20 20:19
Can confirm same issue latest Nvidia, Arch, KDE packages. Only occurs on Wayland
This has been an issue on Wayland since years. I have a  multi-monitor  setup and it used to work fine (ie no artifacts) on one monitor but not the other. Nowdays the artifacts in  the corners appear on both monitors

**Comment by a-parhom** [comment] 2022-05-20 20:51
I can't reproduce this in virtual machine with Wayland. Unfortunately, I'm not able to test it on real hardware now. When I'll such opportunity, I'll look into this.

**Comment by a-parhom** [comment] 2022-05-21 10:10
Well, looks like this happens only on multimonitor setup under Wayland. I'll leave [this link](https://sourceforge.net/p/shapecorners/tickets/4/) here and will return to this issue when I'll have the necessary hardware setup for debugging and testing.

**Comment by Sojiro84** [comment] 2022-05-21 16:48
That tracks. I got 2 DisplayPorts monitors and 1 HDMI monitor connected.

I hope you will be able to fix it!

**Comment by fafafwawe** [comment] 2022-05-21 20:30
Seeing the link you posted they said that this one is working https://github.com/linuxdeepin/dde-kwin/tree/master/plugins/kwineffects/scissor-window 

If I get to my setup I'll  try it out with that

**Comment by Sojiro84** [comment] 2022-05-26 20:47
Just installed the latest master but I am still having the bug.

Also tried rebooting my PC just to be sure everything was freshly loaded and also tried uninstalling and then reinstalling without success.

**Comment by a-parhom** [comment] 2022-05-26 21:22
Can't reproduce with 3 monitors either.

**Comment by Sojiro84** [comment] 2022-05-26 21:44
This is my setup 
![image](https://user-images.githubusercontent.com/13678578/170585064-78d3ba48-e48a-4ac0-a864-c6c2005cf3b7.png)

**Comment by a-parhom** [comment] 2022-05-26 21:50
Can you, please, test this without rotation and with displays in order like 1 to the left, 2 in the middle and 3 to the right? I'm still testing this with virtualbox and multiple rdp connections to virtual monitors, so it's rather hard to test complicated configurations.

**Comment by Sojiro84** [comment] 2022-05-26 21:55
The monitors are 1, 2, 3 connected to my GPU. I just tested setting the portrait monitor back to horizontal, but unfortunately, that didn't solved the issue.

**Comment by a-parhom** [comment] 2022-05-26 21:56
@fafafwawe Can you, please, also test the latest master branch on your setup?

**Comment by a-parhom** [comment] 2022-05-26 21:58
I could reproduce the issue in virtualbox with virtual monitors and the latest commit fixed it for me.

**Comment by a-parhom** [comment] 2022-05-27 18:58
@Sojiro84 Please, check latest commit.

**Comment by Sojiro84** [comment] 2022-05-27 19:31
> @Sojiro84 Please, check latest commit.

It works!

Many thanks!

**Comment by a-parhom** [comment] 2022-05-27 19:32
Thank you for testing! Closing the issue.

**Closed by a-parhom** 2022-05-27 19:32 UTC
Labels: bug

**Comment by fafafwawe** [comment] 2022-06-09 23:36
I still have the issue. Everything up  to  date Arch  linux.  Pulled  from git master this repo. I tried on a fresh  user.

**Comment by a-parhom** [comment] 2022-06-10 06:41
I can't reproduce this after latest changes. Maybe, your nvidia card is the cause, I don't have one to test. Also, could you tell which Plasma version do you have?

**Comment by a-parhom** [comment] 2022-06-10 07:55
And a screenshot might help as well.

**Comment by fafafwawe** [comment] 2022-06-16 19:34
![bug](https://user-images.githubusercontent.com/105948165/174150365-28792a2d-43ef-45f9-ae33-747f68605ec4.png)

5.24.5
It likely is a Nvidia issue since Nvidia has other graphical glitches with Plasma (but not Gnome).  If you enable the Background contrast effect transparency breaks and causes the transparent parts to simply become black.
