### ISSUE TITLE
Outline of borderless window leaves a flickering ghost

### ISSUE THREAD

**Issue by Hibanaw** [a-parhom/LightlyShaders#22] opened 2022-01-30 08:57 UTC
![image](https://user-images.githubusercontent.com/61813396/151693090-a2d626f9-243a-4c04-a5c2-61cb743bac6f.png)

Happens to steam, wps etc
Ghosting disappears when clicking another window

**Comment by a-parhom** [comment] 2022-01-30 09:07
As far as I know, the cause is the same as for #21

**Comment by cheyngoodman** [comment] 2022-01-31 21:41
[YidaozhanYa claims reverting to 0b80af resolves #21.](https://github.com/a-parhom/LightlyShaders/issues/21#issuecomment-1025331666)

I checked out that commit, built and installed it and rebooted. This issue #22 is persistent even on the old commit 0b80af.

Reverting to 0b80af fixed Steam corners, but it also introduced a korner bug. Specifically where the corner shadow is a lighter shade than the window shadow in both Dolphin and VSCode. I think #21 may be specific to corners, where this bug is effected by border shadows.

**Comment by YidaozhanYa** [comment] 2022-02-01 09:15
For me, reverting to this commit solved a lot of SDL and wine apps' dark corner , but some electron apps still have problems

**Comment by a-parhom** [comment] 2022-02-02 22:09
This should be fixed now.

**Comment by cheyngoodman** [comment] 2022-02-02 22:32
The latest commit resolved the issue for me. Thanks!

**Closed** 2022-02-03 07:51 UTC
