### ISSUE TITLE
[v2.0] Corners outline rendering issue, needs improved blending approach 

### ISSUE THREAD

**Issue by YidaozhanYa** [a-parhom/LightlyShaders#70] opened 2022-10-18 12:53 UTC
![图片](https://user-images.githubusercontent.com/73830635/196434230-9f253092-911e-4b6f-aa2b-1339a60ffd83.png)
![图片](https://user-images.githubusercontent.com/73830635/196434618-8aef8668-8410-46bd-a76e-cdfc2428ccc2.png)

---

KDE Plasma: 5.26.0 on X11
Aurorae theme: SierraBreezeEnhanced

LightlyShaders config:
Radius: 10px, Shadow offset: 2px, Corners mode: Rounded corners

SierraBreezeEnhanced config:
Corner radius: 6px (got same issue on 10px and 5px)

**Comment by a-parhom** [comment] 2022-10-18 22:42
Looks like issue with SierraBreezeEnhanced. Make sure to use the latest version.

**Comment by a-parhom** [comment] 2022-10-18 22:52
Since v2.0 does not deal with title bar blur by design (the decoration is expected to do so), I'll close this.

**Comment by YidaozhanYa** [comment] 2022-10-18 23:40
![图片](https://user-images.githubusercontent.com/73830635/196564607-4398880d-9222-46cc-849d-1a6a515cfa50.png)

This bug appears on every corner of the window.

I compiled SierraBreezeEnhanced from [this repository](https://github.com/kupiqu/SierraBreezeEnhanced), it seems that SierraBreezeEnhanced is discontinued before Plasma 5.26. Is the SierraBreezeEnhanced you mentioned also a fork?

**Comment by YidaozhanYa** [comment] 2022-10-18 23:46
![图片](https://user-images.githubusercontent.com/73830635/196565473-933319a7-79d9-447a-ba8a-a1bcd777f8ad.png)

This also happens on stock Breeze Aurorae theme with 5px corner radius.

**Comment by a-parhom** [comment] 2022-10-22 08:54
This is another issue. It's a known rendering issue, I just haven't figured out the best solution to it. Renaming and reopening for now.

**Closed** 2022-10-26 23:36 UTC
Labels: bug
