### ISSUE TITLE
RoundedCorner failing when window behind white background on v2.0 branch

### ISSUE THREAD

**Issue by semarainc** [a-parhom/LightlyShaders#62] opened 2022-09-14 02:29 UTC
Hi,
thank you for your effort on developing this project :D

i have tried v2.0 branch and i would like to report bug regarding the rounded corner bug when window is behind white background, make window fail to render round corner properly

here is screenshot:
![image](https://user-images.githubusercontent.com/19622207/190044783-a22c4a62-f058-4008-b242-b7ca4399cac1.png)

My System Information:
Distro: Manjaro Linux
Plasma : 5.25.5
Display: Wayland
Theme: Breeze Dark

i hope you can look for this issue :D
thanks

**Comment by a-parhom** [comment] 2022-09-14 11:14
This is a duplicate of issue #60. Make sure your decoration radius is equal to LightlyShaders radius.

**Closed by a-parhom** 2022-09-14 11:14 UTC
Labels: duplicate
