### ISSUE TITLE
Does not work in plasma 5.24.1

### ISSUE THREAD

**Issue by Nikita-Presnov** [a-parhom/LightlyShaders#36] opened 2022-02-21 17:21 UTC
Operating System: KDE neon 5.24
KDE Plasma Version: 5.24.1
KDE Frameworks Version: 5.91.0
Qt Version: 5.15.3
Kernel Version: 5.13.0-30-generic (64-bit)
Graphics Platform: X11
Processors: 8 × Intel® Core™ i5-8250U CPU @ 1.60GHz
Memory: 7.4 ГиБ of RAM
Graphics Processor: Mesa Intel® UHD Graphics 620

I even can not see in settings.

**Comment by a-parhom** [comment] 2022-02-21 17:40
It just needs to be recompiled.

**Comment by a-parhom** [comment] 2022-02-21 17:41
Duplicate of #35 .

**Closed by a-parhom** 2022-02-21 17:41 UTC
