### ISSUE TITLE
Error in wayland session

### ISSUE THREAD

**Issue by YidaozhanYa** [a-parhom/LightlyShaders#31] opened 2022-02-13 08:22 UTC
![image](https://user-images.githubusercontent.com/73830635/153745038-81c237ef-a136-409c-9f19-4e2026892af2.png)
Applications' menu is also stroked by this plugin, as in the picture

**Comment by YidaozhanYa** [comment] 2022-02-13 08:26
Desktop Environment: KDE Plasma 5.24 with NVIDIA graphics.
btw, i also hope that applictaion/window blacklist function to be added to this plugin

**Comment by a-parhom** [comment] 2022-02-17 11:18
I'm not quite sure if this effect is compatible with Wayland at all, but I'll try to investigate as soon as I'll have free time.

**Comment by a-parhom** [comment] 2022-02-17 11:20
Adding the blacklist functionality is in plans, I'll try to implement it in some weeks, maybe.

**Comment by a-parhom** [comment] 2022-02-17 11:36
Let's keep the issue open for me not to forget to see what's going on with the plugin on Wayland.

**Comment by YidaozhanYa** [comment] 2022-02-20 11:48
In the latest commit's version, menus on desktop have no borders now, but other menus still have ugly borders.
other features works well in Wayland session now.
Adding the blacklist function and blacklist Qt menus maybe helps

**Comment by YidaozhanYa** [comment] 2022-02-20 11:54
In addition, the border also wrongly appears on IMEs (such as fcitx5).

**Comment by a-parhom** [comment] 2022-02-20 12:14
Default menus are already in the blacklist. Nothing was changed regarding this in latest commits. Maybe, the problem is in KWin Wayland implementation and something was improved in Plasma 5.24.1 itself. Though it's just assumptions.

**Comment by a-parhom** [comment] 2022-02-21 11:52
@YidaozhanYa Please, try the latest changes.

**Comment by a-parhom** [comment] 2022-02-21 21:16
Let's close this, as the menus on Wayland seem to work OK now. Of there are still problems with fcitx5, feel free to open separate issue.

**Closed by a-parhom** 2022-02-21 21:16 UTC
