### ISSUE TITLE
Effect broken

### ISSUE THREAD

**Issue by ramon501** [a-parhom/LightlyShaders#102] opened 2023-05-10 15:15 UTC
It doesnt seem to be working with plasmashell 5.27.5, can you take a look ?

**Comment by Blovien** [comment] 2023-05-11 07:51
I can confirm, the effect doesn't show in the desktop effects, same version of plasma shell.

**Comment by a-parhom** [comment] 2023-05-12 16:55
Duplicate of #29

**Closed by a-parhom** 2023-05-12 16:55 UTC

**Comment by ramon501** [comment] 2023-05-12 17:42
at least to me it doesnt work even after recompiling it, i keep getting this error:
AutoMoc warning
---------------
"SRC:/lightlyshaders.cpp"
includes the moc file "lightlyshaders.moc", but does not contain a Q_OBJECT, Q_GADGET, Q_NAMESPACE, Q_NAMESPACE_EXPORT, K_PLUGIN_FACTORY, K_PLUGIN_CLASS, K_PLUGIN_FACTORY_WITH_JSON or K_PLUGIN_CLASS_WITH_JSON macro.

**Comment by ramon501** [comment] 2023-05-18 23:19
ok i got it working today after updating cmake it seems
