### ISSUE TITLE
Can't find kwin4_lightlyshaders_config (v2.0 branch)

### ISSUE THREAD

**Issue by Yikai-Liao** [a-parhom/LightlyShaders#81] opened 2022-11-16 12:09 UTC
![图片](https://user-images.githubusercontent.com/110762732/202175446-00c2108f-6b53-4c1e-8801-7f36a70d3204.png)
Got following warning when executing cmake
```
CMake Warning at CMakeLists.txt:83 (add_library):
  Cannot generate a safe runtime search path for target
  kwin4_effect_lightlyshaders because files in some directories may conflict
  with libraries in implicit directories:

    runtime library [libxcb.so.1] in /usr/lib may be hidden by files in:
      /opt/anaconda/lib

  Some of these libraries may not be found correctly.
```

When execute `sudo make install` ,  runtime path is set to /opt/anaconda/lib
```
[100%] Built target kwin4_lightlyshaders_config
Install the project...
-- Install configuration: "Debug"
-- Installing: /usr/lib/qt/plugins/kwin/effects/plugins/kwin4_effect_lightlyshaders.so
-- Set runtime path of "/usr/lib/qt/plugins/kwin/effects/plugins/kwin4_effect_lightlyshaders.so" to "/opt/anaconda/lib"
-- Up-to-date: /usr/share/kwin/shaders/1.40/lightlyshaders.frag
-- Installing: /usr/lib/plugins/kwin/effects/configs/kwin4_lightlyshaders_config.so
-- Set runtime path of "/usr/lib/plugins/kwin/effects/configs/kwin4_lightlyshaders_config.so" to "/opt/anaconda/lib"
```

When execute `(kwin_x11 --replace &) ` ,  got the following logs, with a log unrecognized or undefined things 
```
kwin_xkbcommon: XKB: inet:323:58: unrecognized keysym "XF86EmojiPicker"                                                                       ✔  base  
kwin_xkbcommon: XKB: inet:324:58: unrecognized keysym "XF86Dictate"
Module 'org.kde.kwin.decoration' does not contain a module identifier directive - it cannot be protected from external registrations.
OpenGL vendor string:                   NVIDIA Corporation
OpenGL renderer string:                 NVIDIA GeForce RTX 2060/PCIe/SSE2
OpenGL version string:                  3.1.0 NVIDIA 520.56.06
OpenGL shading language version string: 1.40 NVIDIA via Cg compiler
Driver:                                 NVIDIA
Driver version:                         520.56.6
GPU class:                              Unknown
OpenGL version:                         3.1
GLSL version:                           1.40
X server version:                       1.21.1
Linux kernel version:                   5.15.78
Requires strict binding:                no
GLSL shaders:                           yes
Texture NPOT support:                   yes
Virtual Machine:                        no
qt.svg: link #g1000 is undefined!
qt.svg: link #g1000 is undefined!
qt.svg: link #g1000 is undefined!
qt.svg: link #g1000 is undefined!
file:///usr/share/kwin/tabbox/informative/contents/ui/main.qml:123: TypeError: Cannot call method 'longestCaption' of null
```
Finally, when I open system setting of LightlyShaders, it shows that config can't be found.
![图片](https://user-images.githubusercontent.com/110762732/202177023-609a275c-2be0-45b2-aced-3bbf68b10b6c.png)

**Comment by a-parhom** [comment] 2022-11-18 00:30
Looks like a duplicate of #61

**Comment by Yikai-Liao** [comment] 2022-11-19 04:41
> Looks like a duplicate of #61 

It does solve my problem

**Closed** 2022-11-19 07:15 UTC
