### ISSUE TITLE
Add ability to blacklist certain applications

### ISSUE THREAD

**Issue by xNaxdy** [a-parhom/LightlyShaders#101] opened 2023-04-17 17:37 UTC
Some applications that draw their CSDs in a particular way don't play nice with this effect. Rustdesk comes to mind, for instance.

It would be appreciated if there was a possibility to blacklist certain applications from having the effect applied for this reason.

**Comment by luisbocanegra** [comment] 2023-04-17 17:52
Duplicate of #42

**Closed** 2023-04-17 20:33 UTC
