### ISSUE TITLE
Window outline does not follow the Magic Lamp deformation

### ISSUE THREAD

**Issue by gianmarcogg03** [a-parhom/LightlyShaders#2] opened 2021-11-09 18:57 UTC
I'm using Plasma 5.23.2 on Arch Linux and with the shader enabled if I move a window it disappears until I release the mouse button.

https://user-images.githubusercontent.com/28053717/140987134-e8760a36-17d5-4c57-9d9e-43db0688357c.mp4

**Comment by zlotny** [comment] 2021-11-09 21:30
Seems to be related to having "Wobbly Windows" enabled. I've noticed you have it on, and I didn´t, so the error wouldn't appear on my desktop. 
After enabbling Wobbly Windows in fact windows disappear and flicker when moved.

**Comment by gianmarcogg03** [comment] 2021-11-10 18:50
There is another issue, when I take a screenshot with Spectacle of just the currently focused window the screenshot is actually blank. This happens also with Wobbly Windows disabled.

**Comment by ryu-ketsueki** [comment] 2021-11-20 04:50
Can't replicate it, although enabling wobbly windows do make the window blink for a bit then the shader and blur effect disappears, with only the wobbly effect happening. Could be because it requires a specific KWin build and I'm on master so... I dunno

**Comment by a-parhom** [comment] 2021-11-20 22:02
Please try to pull recent changes from the master branch and reinstall the plugin. Now it uses absolutely different approach and this issue should be fixed.

**Comment by ryu-ketsueki** [comment] 2021-11-20 22:30
Just tested it. Goodbye, korners bug!!

**Comment by gianmarcogg03** [comment] 2021-11-21 17:00
![2021-11-21_17-59](https://user-images.githubusercontent.com/28053717/142771655-fdd1a720-40f0-4e17-b0a0-f7dfa038e117.png)
Now this!

**Comment by ryu-ketsueki** [comment] 2021-11-21 20:22
I don't understand. What's wrong with it?

**Comment by a-parhom** [comment] 2021-11-21 20:41
As I can understand, the window outline does not follow the Magic Lamp deformation. But I can't reproduce that on my system. 

Please, tell me what is your videocard, your video driver and Plasma version. Not sure if I can help, but I'll try if I can.

**Comment by zlotny** [comment] 2021-11-21 20:53
It **can't** replicate this on my system either. It looks fine when I enable the Magic Lamp effect:
![image](https://user-images.githubusercontent.com/6155245/142778326-ba0a0971-a436-414f-a021-41ee0925f387.png)

I tried different compositor options, tried both Wayland and X11, tried different options for the outline included in the effect... can't replicate this at all.

Info:
Operating System: Arch Linux
KDE Plasma Version: 5.23.3
KDE Frameworks Version: 5.88.0
Qt Version: 5.15.2
Kernel Version: 5.15.2-zen1-1-zen (64-bit)
Graphics Platform: X11
Processors: 8 × 11th Gen Intel® Core™ i7-1165G7 @ 2.80GHz
Memory: 15,4 GiB of RAM
Graphics Processor: Mesa Intel® Xe Graphics

**Comment by a-parhom** [comment] 2021-11-21 21:14
Not sure, but maybe it is somehow related to issue #6. The current implementation has some things that can (and should) be optimized. And maybe that can cause glitches on older systems. I'll look into it when I'll have time. But I can't guarantee that it will provide big performance improvement, as the new approach of recalculating and rerendering shadows for 4 corners of each window itself is not very efficient at the first place.

**Comment by gianmarcogg03** [comment] 2021-11-23 13:18
I pulled and rebuilt but the problem is still there.

**Comment by a-parhom** [comment] 2021-11-23 14:33
I'm sorry, but I can't reproduce the issue in any way. My fork contains the change, that makes the outline disappear when the window is being transformed. And that is the only behavior that I can see on both of my systems with different settings and themes. 

Are you sure that you have pulled from the right git repo and branch? If so, could you please provide me with some more info? Your video card, driver, Plasma version, distro?

**Comment by gianmarcogg03** [comment] 2021-11-23 18:53
Video card: Radeon RX580
Plasma version: 5.23.3
Distro: Arch Linux

**Comment by a-parhom** [comment] 2022-01-17 11:36
Is the issue still present after latest changes?

**Comment by ryu-ketsueki** [comment] 2022-01-17 14:53
Not with me, at least. Can't replicate with any other effect either

**Comment by a-parhom** [comment] 2022-01-20 16:06
I think we can close this for now. If someone will experience the bug in future, feel free to reopen.

**Closed by a-parhom** 2022-01-20 16:06 UTC
