### ISSUE TITLE
Is there any way to disable it for some apps like blacklisting some apps from it 

### ISSUE THREAD

**Issue by Aneeqasif** [a-parhom/LightlyShaders#23] opened 2022-01-31 20:23 UTC
![image](https://user-images.githubusercontent.com/78728701/151867127-237dff19-36d2-44f7-8dc5-32eb8783adf0.png)

I am using albert launcher and this wierd thing is happening only when i enable this effect any solution?

**Comment by Aneeqasif** [comment] 2022-01-31 20:29
i obsereved it having issues with electron apps like obsidian
![image](https://user-images.githubusercontent.com/78728701/151867975-1ff19e59-272d-447a-9104-29d33716b799.png)

**Comment by YidaozhanYa** [comment] 2022-02-01 09:13
#22

**Comment by a-parhom** [comment] 2022-02-01 15:41
Fixed the issue with albert-launcher in 6396ae35f3506eba33aa785a5bcf36444bc24cc1.
Closing this, as the second part is just a duplicate of #22.

**Closed by a-parhom** 2022-02-01 15:41 UTC
