### ISSUE TITLE
Konsole blur region isn't updated on maximize if "Disable for maximized windows" is enabled on X11

### ISSUE THREAD

**Issue by luisbocanegra** [a-parhom/LightlyShaders#86] opened 2023-01-23 03:24 UTC
Here is a recording of the issue, can't reproduce on Wayland

Pretty sure this is not a 5.26.90 breakage as I've seen it before, but thought it was caused by [kwin-forceblur](https://github.com/esjeon/kwin-forceblur) script.

It turns out that if Konsole's blur option is disabled, blurs are is still shown due to [LightlyShaders](https://github.com/a-parhom/LightlyShaders) being enabled (?), and if  **force-blur** is enabled with **"Blur only the content of window"** it will update the blur region on window size changes making this bug go unnoticed

https://user-images.githubusercontent.com/15076387/213956600-8705c0c1-8684-4538-b5b8-656bc59ff136.mp4

**System details:**
Operating System: Arch Linux 
KDE Plasma Version: 5.26.90
KDE Frameworks Version: 5.102.0
Qt Version: 5.15.8
Kernel Version: 6.1.7-arch1-1 (64-bit)
Graphics Platform: X11
Graphics Processor: Mesa Intel® UHD Graphics 630

**Comment by a-parhom** [comment] 2023-01-28 01:14
To properly fix blur issues we need this API merged: https://invent.kde.org/plasma/kwin/-/merge_requests/3407

**Comment by a-parhom** [comment] 2024-01-07 23:06
This seems to be fixed with plasma6 branch.

**Comment by a-parhom** [comment] 2024-01-26 13:51
Can't reproduce in v2.2 and v.3.0.

**Closed by a-parhom** 2024-01-26 13:51 UTC
