### ISSUE TITLE
CSD windows on 5.27 have an offset outline

### ISSUE THREAD

**Issue by xNaxdy** [a-parhom/LightlyShaders#88] opened 2023-01-31 09:14 UTC
See picture. It seems to be downward vertically offset by a little bit. This affects all CSD windows I have tested (Lutris, Firefox, Thunderbird).

Screenshot was taken on Xorg

![Screenshot_20230131_101156-1](https://user-images.githubusercontent.com/4532582/215718038-a5681452-c90e-4a6c-b64a-02037a2c012f.png)

**Comment by a-parhom** [comment] 2023-01-31 12:20
Can't reproduce on X11 with Firefox or Thunderbird. Maybe, your theme is not compatible. Also, you can try logging out and in again after applying LightlyShaders.

**Comment by xNaxdy** [comment] 2023-01-31 13:07
It worked with the same theme before (Dracula alt style) on 5.26. Different themes have different offsets. Breeze GTK theme is not affected by this at all.

It's definitely theme dependent as you suspected, but still a regression imo.

**Comment by a-parhom** [comment] 2023-01-31 15:53
Fixed in d6d6ba9.

**Closed by a-parhom** 2023-01-31 15:53 UTC
