### ISSUE TITLE
Effect is only active on one workspace

### ISSUE THREAD

**Issue by KristianOde** [a-parhom/LightlyShaders#10] opened 2021-12-07 10:00 UTC
I use 6 workspaces and this effect is only applied to one workspace. If I go to a workspace where it does not work and switch to another window decoration, that workspace will now have the effect applied correctly but all other workspaces will not, including the one where it previously worked. Just changing window decoration settings while in a specific workspace will _fix the issue for that workspace only while disabling it for all other workspaces_.

**Comment by KristianUSN** [comment] 2021-12-07 10:12
Actually, completely closing the applications on the workspaces that are unaffected fixes this issue. So a fresh reboot with this effect active should probably be a solution.

**Comment by a-parhom** [comment] 2021-12-10 20:33
I can reproduce the issue. Will look into it as soon as I have time, maybe a week or two.

**Comment by KristianOde** [comment] 2022-01-09 00:20
I haven't tested extensively but this issue seems to be fixed now. I was sad when a KDE update broke the original LightlyShaders, and this fork looks really gorgeous with the dark mode outlines as well. Thank you for your work 😁

**Comment by KristianOde** [comment] 2022-01-09 09:54
Sadly, it still seems to happen. Most notably when you disable and reenable desktop effects, which is something I do often due to gaming.

**Comment by a-parhom** [comment] 2022-01-09 10:16
Did you build it from the "performance_optimization" branch? The change is not present in the master branch yet.

**Comment by KristianOde** [comment] 2022-01-09 17:05
Oh sorry I missed that, yes that branch seems to work, at least the effect returns properly after disabling and reenabling desktop effects. 

One thing I did notice that I'm not sure was present before was the corner blur bug is present on the bottom corners, but not the top corners.

**Comment by a-parhom** [comment] 2022-01-09 17:35
Can you show a screenshot of the bug?

**Comment by KristianOde** [comment] 2022-01-09 17:40
![image](https://user-images.githubusercontent.com/46893137/148693830-72337200-37ea-45db-b5d5-f5c7f8334a7c.png)
It's hardly noticeable but as far as I can see it's only present on the bottom corners.

**Comment by a-parhom** [comment] 2022-01-09 17:52
Well, it's not blur. It's because the approach of restoring shadows is not perfect and it can play better or worse with some themes, or windows, or radiuses. You can try switching the theme and see if it will change. Also, in this branch all the "shadow restoration magic" is happening on the GPU to gain some performance, and because of the realisation differences the plugin can behave slightly differently.

I think, you could close this issue and open another one for the shadow glitch. Though it doesn't seem to be easy (or even possible) to solve completely. But I'll see if I can improve the results in any way.

**Closed** 2022-01-09 17:58 UTC

**Comment by a-parhom** [comment] 2022-01-16 01:12
@KristianOde It seems that eventually I managed to eliminate shadow glitches completely. Please, try to build from "improve_shadow_rendering" branch.

**Comment by a-parhom** [comment] 2022-01-16 10:41
The changes are now merged to master, actually.
