### ISSUE TITLE
LightlyShaders not shaping bottom corners under cairo-dock

### ISSUE THREAD

**Issue by ramon501** [a-parhom/LightlyShaders#45] opened 2022-05-30 15:01 UTC
It seems to work fine with qt and kde apps but it doesn't seem to work with some apps like firefox and skype, this seems to affect only the bottom corners, top corners gets rounded all the time:

![2022-05-30_11-47](https://user-images.githubusercontent.com/106532546/171018721-e242d390-dedf-4463-83e7-32c094c50739.png)
![2022-05-30_11-51](https://user-images.githubusercontent.com/106532546/171018745-7d2d23bc-e29e-4ce4-8281-63735924932b.png)

**Comment by a-parhom** [comment] 2022-05-30 17:13
I can't reproduce the issue on my system. Can you give some more details? Your Plasma version, if X11 or Wayland is used, your hardware.

**Comment by a-parhom** [comment] 2022-05-30 17:15
And please make sure you are using updated version, as recent commits have bugfixes for some issues.

**Comment by ramon501** [comment] 2022-05-30 17:40
Sure, Plasma 5.24.5, my system is up to date and lightlyshaders as well, i am using X11, some hardware info:
CPU: AMD Phenom 9600 (4) @ 2.300GHz 
GPU: NVIDIA GeForce 210 
Memory: 3176MiB / 3924MiB 
I use Styleproject for plasma desktop, it rounds the top corners of the windows, maybe you might want to test it ?
https://sourceforge.net/projects/styleproject/

**Comment by ramon501** [comment] 2022-06-13 13:37
Yes

**Comment by a-parhom** [comment] 2022-06-18 21:45
If you are using Plank dock it might be the cause of your problems and the latest commit should fix them.

**Comment by ramon501** [comment] 2022-06-19 02:51
no, i use latte dock as a top panel and cairo-dock, and no, updating LightlyShaders did not work, i've been having more luck with firefox now but not that much with skype, skype resizes-increase the windows as you log in and that's when the bottom windows corners no longer gets rounded, and moving firefox windows also seems to stop the bottom windows corners from getting rounded.

**Comment by a-parhom** [comment] 2022-06-19 07:38
Please, try the latest changes, it should fix issues with cairo-dock.

**Comment by ramon501** [comment] 2022-06-19 10:55
So it looks like cairo-dock was the culprit, the effect is working great with the latest commit, if i remember well cairo-dock uses opengl but not really sure.

**Comment by a-parhom** [comment] 2022-06-19 11:17
Ok, since it's been fixed in commit 29027663e96482f2d11cea1642c6b5bf06d6a170 I'm closing this now.

**Closed by a-parhom** 2022-06-19 11:17 UTC
Labels: bug
